### ISSUE TITLE
IPO - First day (Lifetime first day candle) bullish break

### ISSUE THREAD

**Issue by notnapster** [pkjmesra/PKScreener#139]
Ive looked under X13 but have not been able to find the required.

Requesting a scanner to list IPO stock whose first day candle is the All time high candle after 2 days of listing. (Attached are 4 examples). 
I.e. the IPO stock is bearish immediately after listing.

Looking to avoid listing any IPO stocks where the first day candle high has already been broken by candles in the following days.

. 

Based on backtest, a break of first day candle can give about 20% return in 50% cases and 5%Sl in 50%.

Telegram (notnapster)

![Screenshot_2024-08-04-01-04-49-06_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/d0a018fd-1ca0-40a5-be5c-58472be31274)

![Screenshot_2024-08-04-01-05-31-08_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/09beeabd-a86c-4394-b7ce-ad7cef6f2d31)
![Screenshot_2024-08-04-01-05-22-23_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/76584590-b4c2-4d07-9895-8f918de3aa36)
![Screenshot_2024-08-04-01-05-04-17_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/59b8998f-fe4a-44e5-a93e-b29343524cf0)

**Comment by pkjmesra** [comment]
@notnapster - In the examples above, would your expectation be t have all of the stocks in the samples included or is the expectation to include only Awfis space solutions and Krystal integrated because in these two cases, the first candle was the all time high for the first few days after listing, but other examples you've provided do not fit into that criteria (Stanley and Mukka's high was broken on day 2 candle)

Can you please confirm my understanding?
