### ISSUE TITLE
vcp amendment 

### ISSUE THREAD

**Issue by mukundg920** [pkjmesra/PKScreener#156]
In VCP we can do amendment that is 

Strategy -:

Stock must be near its ATH
making VCP pattern and must be currently in consolidating/ Tightening phase

sharing examples of the same with you.

![image](https://github.com/user-attachments/assets/56a79a0e-f910-4853-bbe8-ebf72551a91b)
![image](https://github.com/user-attachments/assets/7fca3941-a676-4a9d-9242-cbf754589f90)
![image](https://github.com/user-attachments/assets/955aef4b-5655-4a3c-b2e3-508491349d1d)

**Comment by pkjmesra** [comment]
>> [mukundg920]
hello sir
will raise on github as well as posting here to bring it in your notice.
In VCP we can do amendment that is 

Strategy -:

Stock must be near its ATH
making VCP pattern and must be currently in consolidating/ Tightening phase

sharing examples of the same with you.
MAHSCOOTER
TVSHLTD 👆
currently this stock is forming the same

>> [PK]
>> Stock must be near its ATH > I'll keep the default range to be within 20% of ATH. This can be configured.
>> [mukundg920]
Correct
>> [PK]
The consolidation is generally the diff %age between highest top and lowest bottom for the given trend. In this image, when you show 11% for leg 1, 5% for leg 2 and 3% for leg 3, what do you exactly mean? How are we calculating the consolidation for each leg?

>> [mukundg920]
VCP can be of 
1,2,3,4 Legs

If the first leg is of 20%

Second must be half of first -> 10% (20/2)

The third leg must be half of the second -> 5 (10/2)

Hence like this the structure gets formed

After formation of all these legs
The price of the stock must go in the consolidation phase that is it gets bounded within a particular range (it can be any %)
Not necessarily to be a perfect HALF but approximately closer to it

Like in MAHSCOOTER -> 11%,5%,3%
>> [PK]
No. That's not the question. The question is one leg consists of prices coming down on the left and going up on the right. 

Now, the consolidation is generally calculated between the highest high of the left price candles and the lowest low of the left side price candles. 

Similarly, for the right side of the price going up, the consolidation percentage is highest high of the right candles and lowest low of right candles.
I think I should then take the highest high of birth the left and right candles of the same leg and lowest low of the leg. There will be two highs and one low. So that way we can get the consolidation percentage of the leg.
This aligns with that understanding

>> [mukundg920]
You can keep everything same as it was in the VCP (7_4) 

Just add on the filter that stock must be in uptrend... Near its ATH ... Rest everything was perfect in that scanner 7_4

>> [PK]
Yeah I get that.

>> [mukundg920]
Yea that way it may be possible

**Comment by pkjmesra** [comment]
Fixed e9f071abeee4aa0a7924c556263bf49ece8576cc . Available in build # 528 and above.
Additional filters: (that can be disabled by entering N as user choice.
<img width="543" alt="Screenshot 2024-08-29 at 3 12 26 PM" src="https://github.com/user-attachments/assets/bf95598c-6d6b-45cc-b545-bdcec8668616">

Results:
<img width="626" alt="Screenshot 2024-08-29 at 3 11 48 PM" src="https://github.com/user-attachments/assets/ce93bd8e-7975-47dd-b31f-ce80596dfd72">
